/* Original collection and category rules, preserved verbatim. */
const QUOTES = [
"The only way it can be called a hit is if you put an S before the H.",
"It's called the American Dream because you have to be asleep to believe it.",
"\"We pretend to work, the government pretends to pay us.\" (Communism)",
"\"Your cats are gonna eat you when you die!\" Buddy, my cats are trying to eat me now",
"Like walking on mud with cement shoes",
"You are legally obligated to tell me if I've somehow turned on read receipts.",
"LA be like we are going to make a city so unwalkable u HAVE to drive, while simultaneously giving you nowhere to park if u DO drive, but if you find parking we will give u a ticket",
"I think the elephant really ties the room together",
"I tell my cat \"I know\" whenever he meows but I'm gonna be honest, I have no idea",
"Its so much nicer to be depressed in a clean room",
"The first 10 minutes of going to anyone's place in LA is them trying to calm down their dog while telling you this never happens",
"if you text me \"we need to talk\" i'm gonna reply \"yes we do\" now we both stressed",
"when someone loses something i like to ask helpful questions like \"where did you last see it?\" and \"where did you put it?\" and \"where is it?\"",
"everyone knows that emotionally the day ends at 330",
"It's always hard to pick a favorite anything, but this Andrea Cohen poem is hands down my favorite poem. (The committee weighs in)",
"You don't hate cats you just can't handle rejection",
"The looker and the cooker",
"Yes, I have a question. First of all, how dare you?",
"I love it when my cat sighs. Like what ails you my little unemployed freeloader",
"You fucked more old Jews than Bernie Madoff",
"You can live in LA and still be 2 hrs away from LA",
"My dick has led me to places I wouldn't even go with a gun",
"I feel like a seafront village after the Vikings have left.",
"Chi semina vento, raccoglie tempesta",
"This is how you play tennis without the net. Sam Harrisism",
"She thinks Monty Python is the evil snake from Harry Potter.",
"She looks like she uses LinkedIn to flirt and Yelp to leave breakup notes.",
"His career trajectory resembles a pancake: flat, forgettable, and entirely dependent on buttering up someone else.",
"The less you know, the more you believe",
"I saw a guy forget his glasses in a cafe once; he came back for them, saw me watching him so, turned to me, and said, \"I'd probably lose my balls if they weren't in a bag.\" To this day, that saying is my favorite.",
"Give a man the reputation of an early riser, and that man can sleep till noon.",
"Orange cats are in a league of their own",
"When you cuddle up to your cat an their lil paw starts going",
"Two bald men fighting over a comb",
"If you find yourself in a hole, stop diggin.",
"You ever send an email and go to the Sent folder so you can \"read it from their perspective\"?",
"I love how cats just slap everything they don't understand.",
"You may think you need a cat, but what you actually need is two cats.",
"Rid me of this meddlesome priest.",
"If you just get the people who already hate Donald Trump to hate him a little more, we can win this thing.",
"People who live in New York think that people who don't live in New York are somehow kidding. \u2014 Updike",
"I found you on the road to home.",
"I've been to hell and back so often that I've got frequent flyer miles.",
"Cats constantly look at you like you just asked them for a ride to the airport.",
"My hobbies include gently bonking my phone against the window while trying to take a picture of the sky.",
"Nothing more suspicious than a good mood.",
"Looks like _____ fucked a ________.",
"You have the vocal range of a tea kettle",
"If you can believe in yourself half as much as you believe in cream cheese",
"She looks like she shops at Auto Zone",
"You know what has zero calories and zero carbs? A nap.",
"Griffith Park is for healing childhood trauma Runyon Canyon is for ignoring it",
"The entire country is awaiting a biopsy result",
"It's fun watching asshat rearrange the chairs on the Titanic.",
"America's wealthiest hemorrhoid",
"A racist voodoo doll made of discarded cat hair",
"A clown made of mummified foreskin and cotton candy",
"A kidney dropped on the floor at a Supercuts",
"States' rights: Not just for racists anymore!",
"Today's high: 54 degrees. Today's low: the current state of American politics.",
"The best house renovation you can do right about now is the addition of a screaming room.",
"It's times like this that one is reminded of King George III's words on American Independence: \"Can't see that ending well\". Quite.",
"She looks like every woman eating lobster on a cruise ship.",
"When Democrats organize a firing squad, they do it in a circle.",
"When you pull your head out of your ass the view is so much better",
"There are more things in Heaven and Earth, Horatio, than are dreamt of in your philosophy.",
"Yes, it's insanely hot in Los Angeles, but at least everyone is rude.",
"Thru thick and thin.",
"If cats were the size of dogs, we'd be fucked.",
"Two cats is a play date; three cats is a riot.",
"It's a shame that fat cats became synonymous with corporate greed because they are one of the cutest kinds of cats!",
"If elected president, the only statues will be of cats like the Egyptians.",
"I wish I was a house cat. No anxiety except for pretending I am starving.",
"I think my cat could drive a car if he was in the right mindset.",
"How do I teach my body that my fight or flight response is supposed to be for life-or-death situations, not answering an email?",
"Human red Solo cup (referring to college bro-looking guys).",
"At what time today did you hit \"Fuck It\"?",
"More people get to kiss you than the pop's ring.",
"She slappeth.",
"All about that conditional love.",
"I believe in science. I also believe 55\u00b0 in October is colder than 55\u00b0 in April.",
"It really be me vs. the pile of clothes in my room.",
"At this point, if a clown invited me into the woods, I would just go.",
"My favorite Christmas song is whatever plays immediately after \"Feliz Navidad.\"",
"Somebody please develop the app \"Why Is There a Helicopter Over My House.\"",
"My cat is busy staring at ghosts until it's time to yell at bugs he can't reach.",
"Generational wealth is when my cat gets to lay around doing nothing all day while I pay for everything.",
"Rearranging the chairs on the Titanic.",
"LA is like if an entire city had airport prices.",
"You should be able to leave reviews for other people's therapists.",
"When the moon hits your eye like a big pizza pie.",
"Password must contain a symbol, a number, an emotional arc, a centralized theme, a big set piece, a male lead \"struggling with inner demons,\" and a strong female character.",
"High on his own supply.",
"Fuck it. This is the year we're saving everything to the desktop.",
"Woke up so today's already started shaky.",
"Pretty excited to show off how a year of being indoors with plenty of time to self-reflect did not make me a better person.",
"Everyone swears that their cat \"acts more like a dog.\"",
"Is yo blood shuga low?",
"What are cats if not lions that gave up persevering?",
"Should I go on a jog in LA, or should I smoke 100 cigarettes?",
"Whenever I do something that's not on my to-do list, I feel a little bit cheated, so I write it down and immediately cross it off.",
"The women in my town can't wait to wear those long sleeve shirts with the thumb holes.",
"Silver facial hair coming in feels a little aggressive.",
"One fun thing I do on Wednesday is spend half the day thinking it's Thursday.",
"The cat would like to know where all of you hid his shit.",
"Normalize calling Lunchables charcuterie.",
"Basically a renaissance painting (Francis with pizza picture).",
"Easy like Sunday morning, tough like Sunday afternoon, full void like Sunday night.",
"What a year we've had this week.",
"Hot single grannies in your area want to bake you fresh pies.",
"Bring all the groceries in at once or die trying.",
"Whoever decided on spelling \"biscuit\" really needs to get their shuit together.",
"I don't like the person I become when I'm tracking a UPS package.",
"The most zen place in the airport is the \"get your shit together\" bench after going through security.",
"Home is where my habits have a habitat.",
"You can be blessed and exhausted.",
"Sunshine returns to San Francisco for the first time in days, wreaking havoc and destruction everywhere it goes.",
"Having Monday off: A poem.",
"Your tone seems very pointed right now.",
"When you scratch a cynic, you'll see a disappointed idealist.",
"I feel I'm in a therapy group being run by my own rapist",
"Okay, yeah. That's a cherry on top of this whole turd cake",
"Didn't those Founding Fuckers ever hear of an odd number?!",
"Why don't you put on your running shoes and get to the fucking point, Jonah?",
"Being Vice President is like being declawed, defanged, neutered, ball-gagged, and sealed in an abandoned coal mine under two miles of human shit! It is a fate worse than death!",
"Time to robust a nut all over this place",
"Siri, why does God allow suffering?",
"Stealing South Carolina is the bedrock of our political system",
"Does he understand the policy? Forgive my concern, but it's a bit like asking if a dog can grasp the concept of Norway.",
"And while you're there, could you do me another favor, please? Could you find a hostel, go there, and take a fucking overdose of barbiturates?",
"I'm sensing a change in management styles. From touchy-feely to smashy-testes.",
"Have you ever Googled your own name? It's like opening a door to a room where everyone tells you how shit you are.",
"What would you call that? Obsessive Repulsive Disorder?",
"He likes to think of himself as more of a thin, white Mugabe.",
"I'm not quite sure what level of reality I'm supposed to be operating on.",
"Good cock, bad cock.",
"All he's doing is depriving a village somewhere of a twat",
"It's all just gone really HBO.",
"This is like a clown running across a minefield!",
"Excuse me while I slip into something a lot more comfortable, like a coma.",
"I heard he's about as useless as a chocolate teapot.",
"This is the fucking Shawshank Redemption. Only there's more tunneling through shit, and no fucking redemption",
"I've got a to-do list that's longer than a fucking Leonard Cohen song.",
"He's so dense that light bends around him",
"You have more nervous tics than a shoe bomber.",
"He is a 12-year-old boy trapped in the body of a 12-year-old girl.",
"You are the worst thing that has happened to this country since food in buckets and maybe slavery!",
"I've seen a salmon in a grizzly's mouth look less panicky than that!",
"If you listen to me instead of your only two brain cells that are too busy butt-fucking each other somewhere in the vast expanses of your misshapen skull, then maybe, Jonah, you might have a chance at becoming the first mentally impaired Frankenstein's monster to ever win an American election.",
"CNN and Fox both say he's critical, but Fox says it with blonder hair and bigger tits.",
"You're about as welcomed here as a turd in a hot tub",
"Too bad you're not counting your missteps, you'd be done by breakfast, right?",
"When does the White House's Most Useless Press Secretary List come out? I can't wait to see who's number one this year.",
"Hey, hunchback! I don't know what you've been trying to do instead of win, but I'm guessing it has the word 'anal' in it.",
"Is my entire presidency about to have its neck snapped by Congressman Lennie here?",
"She has gone full-metal Nixon.",
"You wouldn't know the smart move if it bent you over and fucked you with a Coke bottle.",
"I am the one who got us this far, you sentient enema.",
"You look like Clark Kent if they dug up Christopher Reeves' corpse to play the part.",
"66 percent disapprove. That's everyone in America who's awake right now.",
"See, this is the problem with high-definition. You don't want to see a dick in hi-def.",
"Go, period. Fuck, period. Yourself, exclamation point!",
"You don't get the complexity. You're the world's biggest single-cell organism.",
"Look, I love abortion, okay? I am an abortionado. But I would go pro-life in a fetal fucking heartbeat if it meant winning.",
"We have a saying here at FB: \"Move fast and break things.\" \u2014 Well that's a job well done.",
"Watching you try to be nice is like watching a baby smoke a cigarette. It's kind of cool, but also very disturbing.",
"It's like watching a goat try and use an ATM.",
"Kent majored in fortune cookies.",
"The 60-Foot Virgin",
"Teenage Mutant Ninja Asshole",
"Tinkerballs",
"One Erection",
"Hagrid's Nutsack",
"Ma'am, I don't mean to piss on your bliss...",
"Sometimes I feel like there's a 9-year-old boy inside of you just operating levers.",
"You're about as annoying as a condom filled with fire ants.",
"Middle East? Middle Easy!",
"This goat is not gonna scape itself.",
"I feel like I'm on a life support machine and they keep pulling the plug to charge their phones.",
"I wouldn't let you run a bath without having the Coast Guard and Fire Department standing by \u2014 yet here you are running America.",
"Supercalifragilisticexpialidickcheese",
"The Gates of Hell have opened and you're my plus one.",
"Calm down! Go to a SPA. Take a Pilates class. Go to a fucking church & find someone there who has Xanax and take four of them.",
"People are looking at me and they are whispering... dick-cake.",
"How do you expect me to mingle with this few people? Did Simon mingle with Garfunkle?",
"She's really mediocre. Of all the ocres, she's the medi-est.",
"Are we seriously gonna let the guy with the police sketch face of a rapist tell us what to do?",
"Could you get me a real coffee instead of this fucking beige paint they're serving?",
"The skyscraper of shit has arrived.",
"You are like an earlobe, just there. Just wobbling",
"If you're bored Anthony Bourdain is on CNN eating mac & cheese",
"This isn't a choice like my diet, this is a necessity like my drinking.",
"It feels like Christmas, except... happy!",
"I am so tense, I could crack a walnut with my ass.",
"You're as welcome here as a swastika mom-shaped shit in a synagogue.",
"You're treating the Constitution like it's a build-your-own-pizza menu.",
"Bordello Bill",
"Hanukkah polls higher in Mecca",
"It's always nice to see the most left-swiped face on Tinder.",
"God doesn't giveth with both hands!",
"This is like explaining gravity to a chicken.",
"Yes please, milk, and two heaping spoonfuls of whatever the fuck you're on."
];
const CATEGORY_META = {
  all: { label: 'All Files', note: 'Everything sharp enough to leave a mark.', color: '#ff6b3d' },
  cats: { label: 'Cats', note: 'Feline contempt and domestic royalty.', color: '#f59e0b' },
  la: { label: 'LA', note: 'Municipal despair and parking-lot theology.', color: '#60a5fa' },
  politics: { label: 'Politics', note: 'National decline gift-wrapped as a sentence.', color: '#ef4444' },
  veep: { label: 'Veep', note: 'Maximum shrapnel per syllable.', color: '#f472b6' },
  domestic: { label: 'Domestic Chaos', note: 'Ordinary life, now weaponized.', color: '#34d399' },
  existential: { label: 'Existential', note: 'Melancholy with stage lighting.', color: '#a78bfa' },
  general: { label: 'Wildcard', note: 'General-purpose social damage.', color: '#fb7185' }
};

const FILTER_ORDER = ['all', 'cats', 'la', 'politics', 'veep', 'domestic', 'existential', 'general'];

function getTags(quote) {
  const tags = [];

  if (/\bcat\b|\bcats\b|kitty|kitten|lion|paw/i.test(quote)) tags.push('cats');
  if (/\bLA\b|Los Angeles|Griffith|Runyon/i.test(quote)) tags.push('la');
  if (/Jonah|Kent\b|Congressman Lennie|Mugabe|Middle East\?|Garfunkle|press secretary|presidency|Bordello Bill|Tinkerballs|One Erection|Hagrid's Nutsack|Supercalifragilisticexpialidickcheese|Dick-cake|beige paint|skyscraper of shit|left-swiped face on Tinder/i.test(quote)) tags.push('veep');
  if (/Trump|Democrats|America|American|election|president|government|Constitution|Fox|CNN|South Carolina|racists|abortion|Communism|Founding|politics|King George III/i.test(quote)) tags.push('politics');
  if (/dog|room|email|Sent folder|phone|airport|groceries|desktop|UPS|password|Lunchables|helicopter|therapists?|parking|shoes|biscuit|window|Wednesday|Monday|Sunday|Christmas|coffee|to-do list|jog|cigarettes|bench|habits|package|lunchables/i.test(quote)) tags.push('domestic');
  if (/dream|depressed|hell|anxiety|fight or flight|good mood|idealist|therapy|shaky|blessed and exhausted|biopsy|suffering|better person|life support|disappointed idealist|the day ends/i.test(quote)) tags.push('existential');

  if (!tags.length) tags.push('general');
  return tags;
}
