/* The overview reads the same statement DATA as the existing Ledger tools. */
window.ThresholdLedger=function(){
  if(typeof DATA==='undefined'||document.querySelector('.th-balance-grid'))return;
  const D=DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
  const month=k=>new Date(k+'-15T12:00:00').toLocaleDateString('en-US',{month:'long',year:'numeric'});
  const rowAt=(a,k)=>a.monthly.filter(m=>m.month<=k&&m.balance!==null).at(-1);
  const estimates=k=>D.accounts.filter(a=>rowAt(a,k)?.estimated);
  const end=D.meta.periodEnd,missing=D.accounts.filter(a=>!a.monthly.some(m=>m.month===end&&m.balance!==null&&!m.estimated));
  const oldOverview=$('#view-overview'),oldAccounts=$('#view-accounts'),tabs=$('.tabs');
  const previousView=$('.view.active')?.id.replace('view-','')||'overview';
  oldOverview.id='view-record';oldOverview.classList.remove('active');oldAccounts.id='view-attack';
  const hero=$('.app>.hero'),kpis=$('.app>.kpi-strip');if(kpis)oldOverview.prepend(kpis);if(hero)oldOverview.prepend(hero);
  const oldOverviewTab=$('.tab[data-view="overview"]'),oldAccountsTab=$('.tab[data-view="accounts"]');
  oldOverviewTab.dataset.view='record';oldOverviewTab.textContent='Statement detail';oldOverviewTab.setAttribute('onclick',"switchView('record',this)");
  oldAccountsTab.dataset.view='attack';oldAccountsTab.textContent='Payment priorities';oldAccountsTab.setAttribute('onclick',"switchView('attack',this)");
  const analysis=document.createElement('details');analysis.className='th-analysis-menu';analysis.innerHTML='<summary>Analysis</summary><div></div>';
  $$('.tab').filter(b=>b.dataset.view!=='checking').forEach(b=>analysis.lastElementChild.append(b));
  function tab(id,label){const b=document.createElement('button');b.className='tab';b.dataset.view=id;b.textContent=label;b.onclick=()=>switchView(id,b);return b}
  const primary=tab('overview','Overview'),accountsTab=tab('accounts','Accounts'),activity=$('.tab[data-view="checking"]');activity.textContent='Activity';
  tabs.replaceChildren(primary,accountsTab,activity,analysis);
  analysis.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{analysis.open=false}));
  document.addEventListener('click',e=>{if(!analysis.contains(e.target))analysis.open=false});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')analysis.open=false});
  const overview=document.createElement('section');overview.id='view-overview';overview.className='view';
  overview.innerHTML=`<div class="th-balance-grid"><div><div class="th-balance-label">Revolving balance <small id="th-close-label"></small></div><div class="th-ledger-amount" id="th-balance" aria-live="polite"></div><p class="th-ledger-delta" id="th-balance-delta"></p><select class="th-month" id="th-statement-month" aria-label="Statement month">${[...D.meta.monthKeys].reverse().map(k=>`<option value="${k}">${month(k)}</option>`).join('')}</select><p class="th-balance-note" id="th-balance-note"></p><button class="th-quiet-link" data-record="basis">How this number is counted ↗</button></div><div class="th-ledger-trend"><header><div><h2>The shape of things.</h2><p>Revolving balances at statement close</p></div><div class="th-range" aria-label="Chart range"><button data-range="6" aria-pressed="false">6 months</button><button data-range="12" aria-pressed="true">1 year</button></div></header><div class="th-trend-chart" id="th-ledger-chart"></div></div></div><div class="th-reconcile"><div><span class="th-kicker">Before the next close</span><h2>A few loose ends.</h2><p>Reconciliation from the ${esc(D.meta.updated)} source record.</p></div><div class="th-reconcile-list"><button data-record="statements"><span><strong>Collect the missing statements.</strong><small>${missing.map(a=>esc(a.name)).join(' · ')}</small></span><span aria-hidden="true">↗</span></button><button data-record="payments"><span><strong>Confirm what has cleared.</strong><small>Payments after the close stay separate from the balance.</small></span><span aria-hidden="true">↗</span></button><button data-record="usbank"><span><strong>Check the US Bank payment.</strong><small>Payment confirmation and card conversion remain unverified in this record.</small></span><span aria-hidden="true">↗</span></button></div></div>`;
  const accounts=document.createElement('section');accounts.id='view-accounts';accounts.className='view';accounts.innerHTML=`<div class="th-account-head"><h2>Every account.<br>Nothing buried.</h2><p>Latest recorded balances. Missing statements carry forward; estimates stay labeled.</p></div><div class="th-accounts-filter"><button data-filter="all" aria-pressed="true">All accounts</button><button data-filter="missing" aria-pressed="false">Missing statements (${missing.length})</button></div><div id="th-account-list"></div><p class="th-ledger-footnote">Source updated ${esc(D.meta.updated)}. Select an account for its complete history and source notes.</p>`;
  tabs.after(overview,accounts);
  let selected=end,range=12;
  function renderBalance(){const value=D.totals.debt[selected],i=D.meta.monthKeys.indexOf(selected),prev=D.totals.debt[D.meta.monthKeys[i-1]],parts=value.toLocaleString('en-US',{minimumFractionDigits:2}).split('.');$('#th-balance').innerHTML=`<span class="th-currency">$</span>${parts[0]}<small>.${parts[1]}</small>`;$('#th-balance').setAttribute('aria-label',money(value));$('#th-balance-delta').textContent=i?`${value>=prev?'↗ +':'↘ −'}${money(Math.abs(value-prev))} from ${month(D.meta.monthKeys[i-1])}`:'First month in this record';$('#th-close-label').textContent=D.accounts.some(a=>!a.monthly.some(m=>m.month===selected&&m.balance!==null&&!m.estimated))?'Partial close':'Statement close';$('#th-balance-note').textContent=(selected===end?`${D.accounts.length-missing.length} of ${D.accounts.length} cards closed. `:'')+(estimates(selected).length?estimates(selected).map(a=>`${a.name} includes the ${month(rowAt(a,selected).month)} estimate. `).join(''):'')+'Missing statements carry their last recorded balances. Later payments are not included.';$('#th-statement-month').value=selected;renderChart()}
  function renderChart(){const host=$('#th-ledger-chart'),keys=D.meta.monthKeys.slice(-range),W=Math.max(260,host.clientWidth),H=245,L=12,R=38,T=24,B=35,values=keys.map(k=>D.totals.debt[k]),lo=Math.floor(Math.min(...values)/5000)*5000,hi=Math.ceil(Math.max(...values)/5000)*5000,x=i=>L+i/(keys.length-1)*(W-L-R),y=n=>T+(hi-n)/(hi-lo||1)*(H-T-B);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Monthly revolving balance. Use the labeled points to inspect each month.">`;for(let n=lo;n<=hi;n+=5000)svg+=`<line x1="${L}" x2="${W-R+8}" y1="${y(n)}" y2="${y(n)}" stroke="#3b17202a" stroke-dasharray="3 5"/><text x="${W-2}" y="${y(n)+4}" text-anchor="end" fill="#795e5d" font-size="11">${n/1000}k</text>`;svg+=`<path d="${keys.map((k,i)=>(i?'L':'M')+x(i)+','+y(D.totals.debt[k])).join(' ')}" stroke="#a74729" stroke-width="2.5" stroke-linejoin="round" fill="none"/>`;keys.forEach((k,i)=>{if(W>480||i%2===0||i===keys.length-1)svg+=`<text x="${x(i)}" y="${H-4}" text-anchor="middle" fill="#795e5d" font-size="11">${new Date(k+'-15').toLocaleDateString('en-US',{month:'short'})}</text>`});host.innerHTML=svg+'</svg>'+keys.map((k,i)=>`<button class="th-chart-point" data-month="${k}" aria-label="${month(k)}: ${money(D.totals.debt[k])}${estimates(k).length?', includes '+estimates(k).map(a=>a.name+' estimate').join(', '):''}" aria-pressed="${k===selected}" style="left:${x(i)/W*100}%;top:${y(D.totals.debt[k])/H*100}%"></button>`).join('');host.querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=b.dataset.month;renderBalance()})}
  function renderAccounts(filter='all'){const rows=(filter==='missing'?missing:D.accounts).slice().sort((a,b)=>b.latestBalance-a.latestBalance);$('#th-account-list').innerHTML=rows.map(a=>`<button class="th-account-row" data-account="${esc(a.key)}"><span><strong>${esc(a.name)}</strong><small>${esc(a.issuer)}</small></span><span class="th-account-basis">${month(a.latestMonth)}${missing.includes(a)?'<small>Statement missing · carried forward</small>':''}</span><span class="th-account-money">${money(a.latestBalance)}${rowAt(a,end)?.estimated?'<small>'+month(rowAt(a,end).month)+' estimate · carried forward</small>':''}</span><span aria-hidden="true">↗</span></button>`).join('');$('#th-account-list').querySelectorAll('button').forEach(b=>b.onclick=()=>openCardModal(b.dataset.account))}
  $('#th-statement-month').onchange=e=>{selected=e.target.value;renderBalance()};$$('[data-range]').forEach(b=>b.onclick=()=>{range=Number(b.dataset.range);$$('[data-range]').forEach(x=>x.setAttribute('aria-pressed',x===b));renderChart()});$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));renderAccounts(b.dataset.filter)});
  const dialog=document.createElement('dialog');dialog.className='th-record-dialog';dialog.setAttribute('aria-labelledby','th-record-title');document.body.append(dialog);
  const row=(title,body)=>`<h3>${esc(title)}</h3><p>${esc(body)}</p>`;
  const notes={
    basis:['A statement view, with the gaps visible.','<p>The month is the calendar month of each statement’s closing date. Missing statements carry the last recorded balance. Payments since the close remain separate until confirmed.</p>'+row('Amazon is an estimate','$2,841.49 = $2,772.05 carried forward + $69.44 estimated interest. The August and September statements are missing; purchases are unknown. Actual charges could make the balance higher.')],
    statements:[`${missing.length} statements still missing.`,missing.map(a=>row(a.name,`${month(a.latestMonth)} balance: ${money(a.latestBalance)}${rowAt(a,end)?.estimated?' (estimate carried forward)':''}. ${a.postPeriod?.text||''}`)).join('')],
    payments:['After the statement close.',D.accounts.filter(a=>a.postPeriod).map(a=>row(a.name,a.postPeriod.text)).join('')],
    usbank:['Check the US Bank payment.',row('Recorded status',D.accounts.find(a=>a.key==='ralphs').postPeriod.text)]
  };
  $$('[data-record]').forEach(b=>b.onclick=()=>{const [title,body]=notes[b.dataset.record];dialog.innerHTML=`<button class="th-close" aria-label="Close source record">×</button><h2 id="th-record-title">${title}</h2>${body}<p>Source record: ${esc(D.meta.updated)}. These are dated notes, not a live balance.</p>`;dialog.querySelector('button').onclick=()=>dialog.close();dialog.showModal()});
  let cardOpener=null;
  const originalOpen=window.openCardModal,originalClose=window.closeCardModal;
  window.openCardModal=function(key){cardOpener=document.activeElement;originalOpen(key);const a=D.accounts.find(a=>a.key===key);const foot=$('#ccmFoot');foot.textContent+=' '+(a.postPeriod?.text||'')+' Source snapshot: '+D.meta.updated+'.';if(key==='amazon'){$('#ccmStats .ccm-stat-label').textContent='Balance · August estimate';$('#ccmStats .ccm-stat-val').textContent+=' (estimated)';foot.textContent='Amazon August balance is estimated at $2,841.49 and carried into September. Both statements are missing; actual purchases are unknown. '+foot.textContent;if(window.__ccmChart){window.__ccmChart.data.datasets[0].label='Balance (August estimated)';window.__ccmChart.update('none')}}$('#ccmOverlay .ccm-close').focus()};
  window.closeCardModal=function(){const open=$('#ccmOverlay').classList.contains('open');originalClose();if(open)cardOpener?.focus({preventScroll:true})};
  $('#ccmOverlay').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const visible=[...e.currentTarget.querySelectorAll('button,a[href],input,select,[tabindex="0"]')].filter(el=>el.getClientRects().length);const first=visible[0],last=visible.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}});
  function resolveHash(){if(!location.hash)return;const id=decodeURIComponent(location.hash.slice(1));const node=document.getElementById(id);const view=node?.closest('.view');if(view){const key=view.id.replace('view-','');switchView(key,$(`.tab[data-view="${key}"]`));if(node!==view)requestAnimationFrame(()=>node.scrollIntoView({block:'start'}))}}
  window.addEventListener('hashchange',resolveHash);
  renderAccounts();renderBalance();new ResizeObserver(()=>renderChart()).observe($('#th-ledger-chart'));
  const target=previousView==='accounts'?'accounts':previousView;switchView(target,$(`.tab[data-view="${target}"]`)||primary);if(!location.hash)window.scrollTo({top:0,behavior:'instant'});else resolveHash();
};
